slam_toolbox:
  ros__parameters:
    use_sim_time: false
    update_rate: 1.0
    publish_period: 0.1
    resolution: 0.05
    max_laser_range: 8.0
    scan_topic: /scan
    odom_frame: base_link  # since you don't have odometry, the map can be used as an odom frame
    base_frame: base_link
    mode: mapping
    map_update_interval: 5.0 # 8.0
    max_occupied_threshold: 0.65
    min_free_threshold: 0.196
    minimum_time_interval: 0.5
    transform_publish_period: 0.02
    linear_update: 0.1 # 0.5
    angular_update: 0.1 #0.436
    scan_buffer_size: 10
    scan_buffer_maximum_scan_distance: 8.0
    lookup_transform_timeout_sec: 0.5
    submap:
      number_of_cells: 3500
